nurupishi/views.py
#!/usr/bin/python3
"""routes and templates"""

from flask import (
        Flask,
        flash,
        render_template,
        request, url_for,
        redirect,
        Blueprint,
        current_app
        )
from flask_sqlalchemy import SQLAlchemy
from flask_login import (
    LoginManager,
    current_user,
    login_required,
    UserMixin,
    login_user,
    logout_user
    )
# from flask_mail import Message
from sqlalchemy.exc import IntegrityError
from slqalchemy.orm import Session
from dotenv import load_dotenv
from datetime import datetime
import requests
import os


from nurupishi.forms import (
        RegistrationForm,
        LoginForm,
        RequestResetForm,
        ResetPasswordForm
        )
from nurupishi.app_plugins import bcrypt
from nurupishi import db
from nurupishi.models import Bookmarks, User, Favorites


load_dotenv('cook.env')

views_bp = Blueprint(
        'views_bp',
        __name__,
        template_folder='templates',
        static_folder='static'
        )


@views_bp.route("/")
def index():
    return render_template("base.html")


@views_bp.route("/search", methods=["GET"])
def search():
    """
    fetches users search query returns recipe
    """
    query = request.args.get('query')
    app_id = current_app.config['APP_ID']
    app_key = current_app.config['APP_KEY']
    url = f'https://api.edamam.com/search?q={query}&app_id={app_id}&app_key={app_key}'
    response = requests.get(url)
    response.raise_for_status()
    data = response.json()['hits']
    recipes = []

    for item in data:
        recipe = item['recipe']
        recipes.append(recipe)

    return render_template('search.html', recipes=recipes)


@views_bp.route("/signup", methods=["GET", "POST"])
def signup():
    from nurupishi.models import User
    """
    allows a new user to create an account
    using email, username and a password
    """

    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            email = form.email.data
            password = form.password.data
            username = form.username.data
            creation_date = datetime.utcnow()

            newuser = User(
                username=username,
                email=email,
                password=bcrypt.generate_password_hash(password).decode('utf-8'),
                creation_date=creation_date
            )

            db.session.add(newuser)
            db.session.commit()
            flash(f"Account Succesfully created", "success")
            return redirect(url_for("views_bp.login"))
        except Exception as e:
            flash(e, "danger")
     
    return render_template('auth.html', form=form)


@views_bp.route("/login", methods=["GET", "POST"])
def login():
    """
    Validates user for log in
    """
    from nurupishi.models import User
    form = LoginForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()

            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('views_bp.index'))
            else:
                flash("Invalid Username or password!", "danger")
        except Exception as e:
            flash(e, "danger")

    return render_template('auth.html', form=form)


@views_bp.route("/logout")
@login_required
def logout():
    """
    Allows logged in user to logout
    """
    logout_user()
    return redirect(url_for('views_bp.login'))


@views_bp.route("/myprofile")
@login_required
def userprofile():
    favorites = current_user.favorites.all()
    bookmarks = current_user.bookmarks.all()

    return render_template("myprofile.html", favorites=favorites, bookmarks=bookmarks)


@views_bp.route("/bookmark", methods=["GET"])
def bookmarks():
    from models import User
    with Session() as session:
        user = session.query(User).filter_by(username=session('username')).first()
        bookmarks = session.query(Bookmarks).filter_by(users_id=user.user_id).all()

        return render_template('bookmark.html', bookmarks=bookmarks)


@views_bp.route("/favorites", methods=["GET"])
def favorites():
    from models import User
    with Session() as session:
        user = session.query(User).filter_by(username=session('username')).first()
        favorites = session.query(Favorites).filter_by(users_id=user.user_id).all()

        return render_template('favorites.html', favorites=favorites)


def send_reset_email(user):
    pass
#    token = user.get_reset_token()
 #   msg = Message('Password Reset Request',
  #                sender='noreply@demo.com',
   #               recipients=[user.email])
   # msg.body = f'''To reset your password, visit the following link:
    #    {url_for('views_bp.reset_token', token=token, external=True)}

       # If you did not make this request then simply ignore this email and
      #  no changes will be made
     #   '''


@views_bp.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    """
    function that allows user to request for
    password reset
    """
    if current_user.is_authenticated:
        return redirect(url_for('views_bp.index'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('views_bp.login'))
    return render_template('reset_request.html', form=form)


@views_bp.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    """
    using the token user recieved, password can
    be successfully reset
    else: invalir token or token expired
    """
    if current_user.is_authenticated:
        return redirect(url_for('views_bp.index'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('views_bp.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8'),
        user.password = hashed_password
        db.session.commit()   
        flash('Your password has been updated succesfully!', 'success')
        return redirect(url_for('views_bp.login'))
    return render_template('reset_token.html', form=form)

nurupishi/templates/auth.html
{% extends "base.html" %}
{% block title %}Signup/Login{% endblock%}
{% block content %}
<div class="user-info">
	<form action="{{ request.path }}" method="POST">
	{{ form.csrf_token }}

	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	{% for category, message in messages %}
	<div class="alert alert-{{category}} alert-dismissable fade show" role="alert">
	{{ message }}
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
	{% endfor %}
	{% endif %}
	{% endwith %}

	{% if request.path == '/signup' %}

	{{ form.username(class_="form-control", placeholder="Username")}}<br>

	{% for error in form.username.errors %}
	{{ error }}
	{% endfor %}

	{% endif %}

	{{ form.email(class_="form-control", placeholder="Email")}}<br>

	{% for error in form.email.errors %}
	{{ error }}
	{% endfor %}

	{{ form.password(class_="form-control", placeholder="Password")}}<br>

	{% for error in form.password.errors %}
	{{ error }}
	{% endfor %}

	{% if request.path == '/signup' %}
	{{ form.confirm_password(class_="form-control", placeholder="Confirm Password")}}<br>

	{% for error in form.confirm_password.errors %}<br>
	{{ error }}
	{% endfor %}
	
	{% endif %}

	{{ form.submit(class="btn btn-outline-info") }}
	<p>
		{% if request.path != '/signup' %}
		New here?
		<a href="{{ url_for('views_bp.signup') }}">Signup</a>
		Forgot Password?
		<a href="{{ url_for('views_bp.reset_request') }}">Reset Password</a>
		{% endif %}
	</p>
</div>
{% endblock %}

nurupishi/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}NuruPishi{% endblock %}</title>
 		<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	</head>
	<body>
		<header class="header">
			<div class="nav-title">NP</div>
			<nav>
				<ul class="nav-links">
					<div class="menu">
						<li><a href="{{ url_for('views_bp.index') }}">Search</a></li>
						<li><a href="{{ url_for('views_bp.search') }}">Home</a></li>
						<li><a href="{{ url_for('views_bp.signup') }}">SignUp</a></li>
						<li><a href="{{ url_for('views_bp.login') }}">LogIn</a></li>
			
						{% if current_user.is_authenticated %}
						<li><a href="{{ url_for('views_bp.favorites') }}">Favorite</a></li>
						<li><a href="{{ url_for('views_bp.bookmarks') }}">Bookmark</a></li>
						{% endif %}
					</div>
				</ul>
			</nav>
		</header>
		<main>
			{% block content %}
			<div class="search-container">
				<form action="{{ url_for('views_bp.search') }}" method="get">
					<input type="search" name="query" placeholder="Japanese Pancakes">
					<button type="submit">Search</button>
				</form>
			</div><br>
			{% endblock %}
		</main>
		<div class="footer">
			<footer>
				<p>Author: ruoya<br>
					<a href="mwangiruoya@gmail.com">Email Me</a><br>
					<a href="https://github.com/ru0ya">Github</a><br>
				</p>
			</footer>
		</div>
	</body>
</html>

nurupishi/templates/bookmark.html
{% extends "base.html" %}
{% block title %}Bookmarks{% endblock %}
{% block content %}
<div class="bookmark-container">
	{% for bookmark in bookmarks %}
	<div class="modal fade" id="recipeModal{{ recipe.id }}" tabindex="-1" role="dialog" aria-labelledby="recipeModal{{ recipe.id }}Label" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">

					<img src="{{ recipe.image }}" alt="{{ recipe.label }}" class="modal-img">
					<h5 class="modal-title ml-3" id="recipeModal{{ recipe.id }}Label">{{ recipe.label }}</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<ul>
						{% for ingredient in recipe.ingredients %}
						<li>{{ ingredient.text }}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

<script>
	$(document).ready(function() {
		$('[data-toggle="modal"]').click(function(e) {
			e.preventDefault();
			$($(this).data("target")).modal("show");
		});
	});
</script>

{% endblock %}

nurupishi/templates/favorites.html
{% extends "base.html" %}
{% block title %}Favorites{% endblock %}
{% block content %}
<div class="favorite-container">
	{% for favorite in favorites %}
	<div class="modal fade" id="recipeModal{{ recipe.id }}" tabindex="-1" role="dialog" aria-labelledby="recipeModal{{ recipe.id }}Label" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<img src="{{ recipe.image }}" alt="{{ recipe.label }}" class="modal-img">
					<h5 class="modal-title ml-3" id="recipeModal{{ recipe.id }}Label">{{ recipe.label }}</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<ul>
						{% for ingredient in recipe.ingredients %}
						<li>{{ ingredient.text }}</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

<script>
	$(document).ready(function() {
		$('[data-toggle="modal"]').click(function(e) {
			e.preventDefault();
			$($(this).data("target")).modal("show");
		});
	});
</script>

{% endblock %}

nurupishi/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="search-container">
	<form action="{{ url_for('views_bp.search') }}" method="get">
		<input type="search" name="query" placeholder="Japanese Pancakes">
		<button type="submit">Search</button>
	</form>
</div><br>

<div class="recipe-container">
	{% for recipe in recipes %}
	<div class="recipe">
		<img src="{{ recipe.image }}" alt="{{recipe.label }}">
		<h3>{{ recipe.label }}</h3>
		<ul>
			{% for ingredient in recipe.ingredients %}
			<li>{{ ingredient.text }}</li>
			{% endfor %}		
		</ul>
	</div>
	{% endfor %}
</div>
{% endblock %}

nurupishi/templates/request_reset.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Reset Password</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg is") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg")}}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}


		

nurupishi/templates/reset_token.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Reset Password</legend>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg is") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg")}}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }}
				{% if form.confirm_password.errors %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
				<div class="invalid-feedback">
					{% for error in form.confirm_password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}


		

nurupishi/templates/search.html
{% extends "base.html" %}

{% block title %}Recipe{% endblock %}

{% block content %}
<div class="search-container">
	<form action="{{ url_for('views_bp.search') }}" method="get">
		<input type="search" name="query" placeholder="Japanese Pancakes">
		<button type="submit">Search</button>
	</form>
</div><br>
<div class="recipe-container">
	{% for recipe in recipes %}
	<div class="modal-header">
		<img src="{{ recipe.image }}" alt="{{ recipe.label }}">
		<h5>{{ recipe.label }}</h5>
		<ul>
			{% for ingredient in recipe.ingredients %}
			<li>{{ ingredient.text }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endfor %}
</div>

{% endblock %}

nurupishi/templates/test.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}Recipe App{% endblock %}</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	</head>
	<body>
		<nav class="navbar">
			<div class="logo">NP</div>
			<ul class="nav-links">
				<div class="menu">
					<li><a href="{{ url_for('search') }}">Search</a></li>
					{% endif %}
				</div>
			</ul>
		</nav>
		<main>
			{% block content %}{% endblock %}
		</main>
	</body>
</html>

nurupishi/templates/user_profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="content-section">
	<div class="media">
		<div class="media-body">
			<h2 class="account-heading">{{ current_user.username }}</h2>
			<p class="text-secondary">{{ current_user.email }}</p>
			<p class="text-secondary">{{ current_user.password }}</p>
		</div>
	</div>
</div>
{% endblock content %}